### ISSUE TITLE
Fails when github mode but no publish info

### ISSUE THREAD

**Issue by dsinghvi** [fern-api/fern-java#215]
```java
java.lang.NullPointerException: null
at com.fern.java.AbstractGeneratorCli.runInGithubMode(AbstractGeneratorCli.java:136)
at com.fern.java.AbstractGeneratorCli$1.visitGithub(AbstractGeneratorCli.java:91)
at com.fern.java.AbstractGeneratorCli$1.visitGithub(AbstractGeneratorCli.java:75)
at com.fern.generator.exec.model.config.OutputMode$InternalGithubValue.visit(OutputMode.java:168)
at com.fern.generator.exec.model.config.OutputMode.visit(OutputMode.java:88)
at com.fern.java.AbstractGeneratorCli.run(AbstractGeneratorCli.java:75)
at com.fern.java.client.ClientGeneratorCli.main(ClientGeneratorCli.java:200)
```

**Comment by dsinghvi** [comment]
This issue was fixed in the following PRs: 
- PR https://github.com/fern-api/fern-java/pull/217
- PR https://github.com/fern-api/fern-java/pull/216
